"USEFUL COMMANDS

"SET GUI
":set guioptions-=m
":set guioptions-=T 
"
"SET WORKINGDIREKTORY TO CURRENT
":cd %:p:h
"
"SEARCH
"%s//
"
"CENTER
"zz
"
"HIGH MIDDLE LOW
"H M L
"
"JUMP TO BRACKET
"%
"
"JUMP TO WORD UNDER CURSER
"* #
"
"OPEN DOKUMENTATION
"^k

"PLUG-IN:

"syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Nerdtree
map <C-n> :NERDTreeToggle<CR>
execute pathogen#infect()
syntax on
filetype plugin indent on



" basics
set noswapfile    " http://robots.thoughtbot.com/post/18739402579/global-gitignore#comment-458413287
set history=50
set ruler         " show the cursor position all the time
set showcmd       " display incomplete commands
set incsearch     " do incremental searching
set laststatus=2  " Always display the status line
set autowrite     " Automatically :write before running commands

" Jump to last known position
augroup vimrcEx
  autocmd!
  autocmd BufReadPost *
    \ if &ft != 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif

" Shift and tabs
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set noexpandtab
set linebreak

" Make all Pretty
set guifont=Monospace\ 8 
syntax on
colorscheme solarized
set guioptions-=m
set guioptions-=T 
set listchars=tab:▸\

" Underline current line
set cursorline
hi CursorLine guibg=NONE gui=underline	

" Make it obvious where 80 characters is
highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn','\%81v', 100)

" Get rid of my habbits
nnoremap <Left> :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up> :echoe "Use k"<CR>
nnoremap <Down> :echoe "Use j"<CR>

" Use relative Numberlines:
set relativenumber
set numberwidth=2
let s:pattern = '^\(.* \)\([1-9][0-9]*\)$'
let s:minfontsize = 6
let s:maxfontsize = 16
